name: Publish

on:
  release:
    types: 
      - created

  workflow_dispatch:

jobs:
  test:
    name: "Test"
    uses: ./.github/workflows/test.yml

  publish:
    name: "Publish Packages"
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://npm.pkg.github.com"
          scope: "@zenz-solutions"
      - run: npm ci
      - run: | 
            cd packages
            for package in */; do
              cd "$package"
              npm publish || true
              sleep 10
              cd ..
            done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
